# Generated by Django 5.1.1 on 2024-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Mr.', 'Mister'), ('Ms.', 'Miss')], max_length=3),
        ),
    ]
